version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: orders_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orders_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: orders_app
  #   environment:
  #     DB_PORT: 5432
  #     DB_HOST: postgres
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #   networks:
  #     - my-network

networks:
  my-network: